#!/bin/zsh

mkdir expat-build
mkdir expat-install
cd expat-build
../expat-${Vw_EXPAT}/configure --host=x86_64-w64-mingw32
make
INSTALL_ROOT=$PWD/../expat-install make install
cd ../expat-install
x86_64-w64-mingw32-strip --remove-section=.comment --remove-section=.note --strip-unneeded **/*.dll

