#!/bin/zsh

mkdir gdb-build
mkdir gdb-install
cd gdb-build
../gdb-${V_GDB}/configure \
    --host=x86_64-w64-mingw32 \
    --prefix=/c/Users/Public/raspbian10 \
    --program-prefix=arm-raspbian10-linux-gnueabihf- \
    --target=arm-linux-gnueabihf \
    --with-sysroot=/c/Users/Public/raspbian10/sys-root \
    --with-build-sysroot=/usr/local/raspbian10-toolchain/sys-root \
    --enable-plugins \
    --disable-nls \
    --with-pkgversion="GDB for Raspbian 10" \
    --disable-nls \
    --with-expat \
    --with-libexpat-prefix=$PWD/../expat-install/usr/local/
# --with-python=$PWD/../makes/python-config-gdb
make -j4
DESTDIR=$PWD/../gdb-install make install
cd ../gdb-install
x86_64-w64-mingw32-strip --remove-section=.comment --remove-section=.note --strip-unneeded **/*.exe
