#!/bin/zsh

mkdir binutils-build
mkdir binutils-install
cd binutils-build
../binutils-${V_BINUTILS}/configure \
    --prefix=/usr/local/raspbian9-toolchain \
    --program-prefix=arm-raspbian9-linux-gnueabihf- \
    --target=arm-linux-gnueabihf \
    "--with-pkgversion=GNU Binutils for Raspbian 9" \
    --enable-poison-system-directories \
    --with-sysroot=/usr/local/raspbian9-toolchain/sys-root \
    --disable-nls \
    --enable-lto \
    --disable-werror
make -j3
DESTDIR=$PWD/../binutils-install make install
cd ../binutils-install
