#!/bin/bash
source ../versions.sh

export CFLAGS="-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security"
export CPPFLAGS="-D_FORTIFY_SOURCE=2"
export CXXFLAGS="-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security"
export FFLAGS=-"g -O2"
export LDFLAGS=""

export CFLAGS_FOR_TARGET="-g -O2 --param=ssp-buffer-size=4 -Wformat -Wformat-security"
# BUG: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61164
# so we just disable it
export CPPFLAGS_FOR_TARGET=""
export CXXFLAGS_FOR_TARGET="-g -O2 --param=ssp-buffer-size=4 -Wformat -Wformat-security"
export FFLAGS_FOR_TARGET="-g -O2"
export LDFLAGS_FOR_TARGET="-Wl,-Bsymbolic-functions -Wl,-z,relro"

echo "Extracting GCC..."
tar xf ../gcc-${V_GCC}.tar.gz
echo "Extracting MPFR..."
tar xf ../mpfr-${V_MPFR}.tar.bz2
echo "Extracting MPC..."
tar xf ../mpc-${V_MPC}.tar.gz
echo "Extracting GMP..."
tar xf ../gmp-${V_GMP}.tar.bz2
echo "Extracting CLOOG..."
tar xf ../cloog-${V_CLOOG}.tar.gz
echo "Extracting ISL..."
tar xf ../isl-${V_ISL}.tar.bz2
echo "Extracting GDB..."

echo "Patching GCC..."
sh -c "cd gcc-${V_GCC} && patch -p2 < ../../patches/gcc/g++-multiarch-incdir.diff"
patch -p0 < ../patches/gcc/config

mv cloog-${V_CLOOG} gcc-${V_GCC}/cloog
mv isl-${V_ISL} gcc-${V_GCC}/isl
mv mpfr-${V_MPFR} gcc-${V_GCC}/mpfr
mv mpc-${V_MPC} gcc-${V_GCC}/mpc
mv gmp-${V_GMPf} gcc-${V_GCC}/gmp

mkdir gcc-build
mkdir gcc-install
cd gcc-build
../gcc-${V_GCC}/configure \
    --enable-threads=posix \
    --program-prefix=arm-raspbian10-linux-gnueabihf- \
    --target=arm-linux-gnueabihf \
    --with-arch=armv6 \
    --with-float=hard \
    --with-fpu=vfp \
    --with-specs='%{save-temps: -fverbose-asm} %{funwind-tables|fno-unwind-tables|mabi=*|ffreestanding|nostdlib:;:-funwind-tables}' \
    --enable-languages=c,c++ \
    --with-default-libstdcxx-abi=new \
    --enable-libstdcxx-time=yes \
    --enable-shared \
    --enable-lto \
    --disable-nls \
    "--with-pkgversion=GCC for Raspbian 10" \
    --with-cloog \
    --enable-multilib \
    --enable-multiarch \
    --prefix=/usr/local/raspbian10-toolchain \
    --with-gcc-major-version-only \
    --with-sysroot=/usr/local/raspbian10-toolchain/sys-root \
    --disable-libmudflap \
    --libdir=/usr/local/raspbian10-toolchain/sys-root/usr/lib \
    --with-gxx-include-dir=/usr/local/raspbian10-toolchain/sys-root/usr/include/c++/8 \
    --with-system-zlib \
    || exit $?
make -j3 all-gcc || exit $?
DESTDIR=$PWD/../gcc-install make install-gcc || exit $?

cd ../gcc-install


