#!/bin/zsh

echo "Patching binutils..."
sh -c "cd binutils-${V_BINUTILS} && patch -p1 < ../../patches/binutils/129_multiarch_libpath.patch"

APPEND_TOOLLIBDIR=yes
export APPEND_TOOLLIBDIR

mkdir binutils-build
mkdir binutils-install
cd binutils-build
../binutils-${V_BINUTILS}/configure \
    --prefix=/usr/local/raspbian10-toolchain \
    --program-prefix=arm-raspbian10-linux-gnueabihf- \
    --target=arm-linux-gnueabihf \
    "--with-pkgversion=GNU Binutils for Raspbian 10" \
    --enable-poison-system-directories \
    --with-sysroot=/usr/local/raspbian10-toolchain/sys-root \
    --disable-nls \
    --enable-lto \
    --disable-werror
make -j3
DESTDIR=$PWD/../binutils-install make install
cd ../binutils-install
