#!/bin/zsh

rm -rf tree-install
mkdir tree-install
rsync gcc-install/ tree-install -a --copy-links
rsync binutils-install/ tree-install -a --copy-links
rsync sysroot-install/ tree-install -a --copy-links
rsync gdb-install/ tree-install -a --copy-links
du -hs .

pushd tree-install
strip usr/local/raspbian10-toolchain/bin/*
strip usr/local/raspbian10-toolchain/arm-*/bin/*
find usr/local/raspbian10-toolchain/libexec -type f |xargs strip

# Remove non prefixed gcc
rm /usr/local/raspbian10-toolchain/bin/arm-linux-gnueabihf-gcc*
popd

du -hs .
